import { describe, expect, it } from 'vitest'
import { buildPortsFromCatalog, extractCatalogTags } from './catalogAutofill'
import type { ApiCatalogItemDetails } from './api'

function details(overrides: Partial<ApiCatalogItemDetails> = {}): ApiCatalogItemDetails {
  return {
    provider: 'MOCK',
    external_id: 'v1|test|0',
    title: 'Interface Test',
    images: [],
    specs: {},
    ...overrides,
  }
}

describe('catalogAutofill', () => {
  it('builds generic input/output ports from specs counts', () => {
    const item = details({
      specs: {
        'Number of Inputs': '2',
        'Number of Outputs': '3',
      },
    })
    const ports = buildPortsFromCatalog(item)
    expect(ports).toHaveLength(5)
    expect(ports[0]).toEqual({ label: 'Input 1', type: 'Input', patchbayId: null })
    expect(ports[2]).toEqual({ label: 'Output 1', type: 'Output', patchbayId: null })
  })

  it('caps autogenerated ports to 16 per side', () => {
    const item = details({
      specs: {
        'Number of Inputs': '99',
        'Number of Outputs': '20',
      },
    })
    const ports = buildPortsFromCatalog(item)
    expect(ports).toHaveLength(32)
  })

  it('extracts normalized tags from known specs', () => {
    const item = details({
      specs: {
        Condition: 'Used',
        Connectivity: 'USB-C',
        'Sample Rate': '96 kHz',
        'Phantom Power': 'Yes',
      },
    })
    const tags = extractCatalogTags(item)
    expect(tags).toContain('condition:used')
    expect(tags).toContain('connectivity:usb-c')
    expect(tags).toContain('sample-rate:96-khz')
    expect(tags).toContain('phantom-power')
  })
})
