export const strings = {
  app: {
    name: 'Pepper',
    tagline: 'Studio patchbay control',
    loadingData: 'Loading data...',
    retry: 'Retry',
    syncing: 'Syncing...',
    synced: 'Synced',
    syncIssue: 'Sync issue',
    authDegradedTitle: 'Session validation unavailable.',
    authDegradedMessage: 'The server cannot validate sessions right now. Please retry shortly.',
    export: 'Export',
    exportDisabled: 'Export not included in your access.',
    help: 'Help',
    shortcuts: 'Shortcuts',
    comingSoon: 'Coming soon',
    dismiss: 'Dismiss',
    closeSymbol: 'x',
    copyAccessInfo: 'Copy access request info',
    accessDisabledTitle: 'Access not enabled',
    accessDisabledMessage: 'Your access is not enabled for this organization.',
  },
  nav: {
    patchbay: 'Patchbay',
    devices: 'Devices',
    nodeView: 'Graph',
    portability: 'Portability',
  },
  portability: {
    title: 'Data Portability',
    subtitle: 'Export and import workspace bundles with preview and conflict controls.',
    exportTitle: 'Export',
    importTitle: 'Import',
  },
  confirm: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    overwriteTitle: 'Overwrite patch point?',
    overwriteMessage: (deviceName: string, portLabel: string) =>
      `This slot is already connected to ${deviceName} - ${portLabel}. Overwrite it?`,
    deleteDeviceTitle: 'Delete device?',
    deleteDeviceMessage: (deviceName: string) =>
      `Delete ${deviceName}? This cannot be undone.`,
  },
  toast: {
    linkedSuccess: (deviceName: string, portLabel: string, patchbayId: number) =>
      `Linked ${deviceName} ${portLabel} -> Patch #${patchbayId}.`,
    linkFailed: 'Linking failed. Please try again.',
    unlinkFailed: 'Unlink failed. Please try again.',
    loadFailed: 'Failed to load data. Please retry.',
    deviceSaved: 'Device saved.',
    deviceDeleted: 'Device deleted.',
    deviceSaveFailed: 'Failed to save device.',
    deviceDeleteFailed: 'Failed to delete device.',
    imageParseFailed: 'Image parsing failed. Try a clearer, well-lit photo.',
    sessionExpired: 'Sesión expirada. Por favor, volvé a iniciar sesión.',
    noPermission: 'No tenés permisos para acceder a estos datos.',
    authServiceUnavailable: 'El servidor no puede validar la sesión ahora. Intentá de nuevo en unos minutos.',
    networkTimeout: 'La solicitud tardó demasiado. Verificá tu conexión y reintentá.',
    limitReached: 'Límite alcanzado. Intentá más tarde o actualizá tu plan.',
    entitlementRequired: 'Tu plan no incluye esta función.',
    quotaExceeded: 'Se alcanzó el cupo mensual de IA.',
    paymentRequired: 'Se requiere una suscripción activa.',
    copySuccess: 'Copied.',
    copyFailed: 'Copy failed. Please try again.',
  },
  patchbay: {
    linkingBanner: (deviceName: string, portLabel: string) =>
      `Select a patch point for: ${deviceName} - ${portLabel}.`,
    linkingFallback: 'Select a patch point to link.',
    cancel: 'Cancel',
    showingConnection: (left: number, right: number) =>
      `Showing connection: #${left} <-> #${right}`,
    clearHighlights: 'Clear',
    searchPlaceholder: 'Search patchbay (point or device)...',
    patchPointTitle: (id: number) => `Patch Point #${id}`,
    nameLabel: 'Name',
    descriptionLabel: 'Description',
    typeLabel: 'Type',
    connectionLabel: 'Connection',
    connectedTo: 'Connected to',
    portLabel: 'Port',
    unlink: 'Unlink',
    notConnected: 'Not connected',
    linkDevice: 'Link device',
    close: 'Close',
    linkDeviceTitle: (id: number) => `Link device to point #${id}`,
    searchDevicesPlaceholder: 'Search devices...',
    occupiedTag: (id: number) => `(#${id})`,
    tooltip: (deviceName: string, portLabel: string) => `${deviceName} - ${portLabel}`,
    legendTitle: 'Legend',
    legendLinked: 'Linked',
    legendOpen: 'Open',
    legendMatch: 'Search match',
    legendHighlight: 'Highlighted',
    rowLabels: ['A', 'B'],
    rowLabel: (label: string) => `Row ${label}`,
    columnLabel: (label: number) => `Col ${label}`,
    linkDeviceAction: 'Link to device',
  },
  devices: {
    title: 'Devices',
    searchPlaceholder: 'Search devices...',
    addDevice: 'Add Device',
    portsCount: (count: number) => `${count} Ports`,
    typeLabel: 'Type',
    categoryLabel: 'Category',
    idLabel: 'ID',
    portsConfig: 'Ports Configuration',
    linkedTo: (patchbayId: number) => `Linked to #${patchbayId}`,
    goToPatch: (patchbayId: number) => `Go to patch #${patchbayId}`,
    unlink: 'Unlink',
    connected: 'Connected',
    notConnected: 'Not connected',
    link: 'Link',
    deleteDevice: 'Delete Device',
    closeDetail: 'Close',
    editDevice: 'Edit Device',
    addNewDevice: 'Add New Device',
    tabManual: 'Manual',
    tabAutoDetect: 'Auto-detect',
    nameLabel: 'Name',
    namePlaceholder: 'Device name',
    typePlaceholder: 'Select type',
    subtypePlaceholder: 'Subtype (optional)',
    portsLabel: 'Ports',
    addPort: '+ Add Port',
    portNamePlaceholder: 'Port name',
    removePort: 'Remove',
    noPorts: 'No ports added yet.',
    resetForm: 'Reset Form',
    updateDevice: 'Update Device',
    createDevice: 'Create Device',
    aiHelp: 'Upload a device photo; we will detect ports and create a draft.',
    aiUpload: 'Upload or take photo',
    aiProcessing: 'Analyzing image...',
    aiDraftReady: 'Draft ready. Review and edit before saving.',
    aiReviewDraft: 'Review draft',
    aiNotIncluded: 'AI detection is not included in your access.',
    aiQuotaUsed: (used: number, limit: number) => `AI detections this month: ${used} / ${limit}`,
    aiQuotaLimit: (limit: number) => `Monthly AI detections limit: ${limit}`,
    aiQuotaRemaining: (remaining: number, limit: number) => `AI detections remaining this month: ${remaining} / ${limit}`,
    aiSteps: {
      upload: '1 Upload',
      processing: '2 Processing',
      review: '3 Review',
    },
    imageLoading: 'Cargando...',
    imageLoadFailed: 'Error al cargar',
    imageMissing: 'Sin imagen',
    imageNoAccess: 'Sin permisos',
    imageUnauthorized: 'Sesión expirada',
    imageTimeout: 'Tiempo agotado',
    addPortLabel: (index: number) => `Port ${index}`,
    validation: {
      addPortFirst: 'Add at least one port.',
      nameRequired: 'Device name is required.',
    },
    saving: 'Saving...',
    portTypes: {
      Input: 'Input',
      Output: 'Output',
      Other: 'Other',
    },
  },
  connections: {
    title: 'Connection Finder',
    subtitle: 'Select two device ports to see which patch points to cable.',
    tabs: {
      finder: 'From / To',
    },
    origin: 'Origin',
    destination: 'Destination',
    sideALabel: 'A',
    sideBLabel: 'B',
    searchPlaceholder: 'Search device or port...',
    unlinked: 'Unlinked',
    noResults: 'No results found',
    patchbayLabel: 'Patchbay',
    notLinkedWarning: 'Not linked to patchbay',
    swapTitle: 'Swap',
    clearSelection: 'Clear selection',
    swapLabel: 'Swap',
    resultSuccessTitle: 'Connection found',
    resultErrorTitle: 'Cannot connect',
    successBadge: 'OK',
    errorBadge: 'NO',
    cableLabel: 'Cable',
    resultInstruction: (a: number, b: number) =>
      `Connect patch #${a} (source) to patch #${b} (destination).`,
    goToPatchbay: 'View highlighted patch points',
    linkNow: 'Link this port now',
    linkNowFor: (label: string) => `Link ${label}`,
    copyInstruction: 'Copy instruction',
    copySuccess: 'Instruction copied.',
    copyFailed: 'Copy failed. Please try again.',
    linkReturnHint: 'Port linked. Continue to get patch instructions.',
    linkRequiredTitle: 'Link required',
    linkRequiredHint: 'Map the missing port to a patch point to get the instruction.',
    pickPatchPoint: 'Select patch point',
    mapPort: 'Map port',
    patchPointOption: (id: number, name: string) => `#${id} - ${name}`,
    hint: 'Link ports to patch points from the Devices tab first.',
    emptyTitle: 'Pick a source and destination port to see the cable path.',
    emptyIcon: '...',
    errorBothUnlinked: 'Neither port is linked to the patchbay.',
    errorUnlinked: (label: string) => `${label} is not linked to the patchbay.`,
  },
}

export type Strings = typeof strings
